[workspace]
resolver = "2"
members = [
    "packages/ui",
    "packages/web",
    "packages/desktop",
    "packages/mobile",
    "packages/api",
]

[workspace.dependencies]
# dioxus-workbench requires >= 0.7.10
dioxus = { version = "0.7.10" }
dioxus-workbench = { version = "0.1.0" }

# workspace
ui = { path = "packages/ui" }
api = { path = "packages/api" }
